import 'package:chronowarden/models/changelog.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('parseChangelog', () {
    test('parses date groups and entries, newest first', () {
      const md = '''
# Changelog

<!-- Generated by tool/generate_changelog.sh from the git history.
     Do not edit by hand — update the script or its output instead. -->

## 2026-10-09

- Rework leave-time notifications (`f8e9290`)

## 2026-10-02

- Add report-issue button to the app bar (`3b5a2fe`)
- Open source: MIT license (`ebf1c76`)
''';

      final groups = parseChangelog(md);
      expect(groups, hasLength(2));
      expect(groups.first.date, '2026-10-09');
      expect(groups.first.entries, hasLength(1));
      expect(
        groups.first.entries.first.text,
        'Rework leave-time notifications',
      );
      expect(groups.first.entries.first.hash, 'f8e9290');
      expect(groups.last.date, '2026-10-02');
      expect(groups.last.entries, hasLength(2));
      expect(groups.last.entries[1].text, 'Open source: MIT license');
    });

    test('ignores the header and comment lines', () {
      const md = '''
# Changelog

Some intro text.

## 2026-01-01

- First change
''';
      final groups = parseChangelog(md);
      expect(groups, hasLength(1));
      expect(groups.single.entries.single.text, 'First change');
      expect(groups.single.entries.single.hash, isNull);
    });

    test('keeps entries without a hash', () {
      final groups = parseChangelog('## 2026-01-01\n\n- No hash here\n');
      expect(groups.single.entries.single.text, 'No hash here');
      expect(groups.single.entries.single.hash, isNull);
    });

    test('only accepts 7-40 char hex hashes', () {
      final groups = parseChangelog(
        '## 2026-01-01\n\n- Short (`abc`)\n- Long (`zzzzzzzz`)\n',
      );
      expect(groups.single.entries[0].text, 'Short (`abc`)');
      expect(groups.single.entries[0].hash, isNull);
      expect(groups.single.entries[1].text, 'Long (`zzzzzzzz`)');
      expect(groups.single.entries[1].hash, isNull);
    });

    test('ignores bullets before any date heading', () {
      final groups = parseChangelog('- orphan bullet\n\n## 2026-01-01\n\n- real\n');
      expect(groups, hasLength(1));
      expect(groups.single.entries.single.text, 'real');
    });

    test('returns empty for input with no entries', () {
      expect(parseChangelog('# Changelog\n\nnothing here\n'), isEmpty);
      expect(parseChangelog(''), isEmpty);
    });
  });
}
