name: chronowarden
description: "Personal time-banking & overtime protection system."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.0.0
  flutter_svg: ^2.3.0
  shared_preferences: ^2.0.0
  cryptography: ^2.0.0
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - chronowarden.png
    - chronowarden.svg
