import 'dart:convert';

/// Metadata about a build, generated by `tool/generate_build_info.sh`.
///
/// The running app ships one copy as the `build_info.json` asset; the same
/// JSON is served by nginx at `/version.json`. Comparing the two is how the
/// app detects that a newer build has been deployed.
class BuildInfo {
  /// App version, from `pubspec.yaml`.
  final String version;

  /// Short git commit the build was produced from (e.g. "b1245a9").
  final String commit;

  /// Build time, UTC ISO-8601.
  final String builtAt;

  const BuildInfo({
    required this.version,
    required this.commit,
    required this.builtAt,
  });

  /// True when this is a real build with a usable commit id (not a local/dev
  /// build where git metadata was unavailable).
  bool get isKnown => commit.isNotEmpty && commit != 'dev';

  /// Parse the JSON produced by the generator. Returns null for malformed or
  /// unexpected input, so callers can simply ignore it.
  static BuildInfo? parse(String raw) {
    try {
      final decoded = jsonDecode(raw);
      if (decoded is! Map) return null;
      return BuildInfo(
        version: (decoded['version'] as String?) ?? '',
        commit: (decoded['commit'] as String?) ?? '',
        builtAt: (decoded['built_at'] as String?) ?? '',
      );
    } catch (_) {
      return null;
    }
  }
}

/// Decide whether the running build should prompt the user to reload.
///
/// Prompt only when both builds are known, they differ, and the user has not
/// already dismissed this exact server build.
bool isUpdateAvailable({
  required BuildInfo? running,
  required BuildInfo? server,
  String? dismissedCommit,
}) {
  if (running == null || server == null) return false;
  if (!running.isKnown || !server.isKnown) return false;
  if (running.commit == server.commit) return false;
  if (dismissedCommit == server.commit) return false;
  return true;
}
