/// An invite token generated by an admin. Maps to the [invites] table.
class Invite {
  final String? id;
  final String? createdBy;
  final String? email;
  final String token;
  final bool used;
  final String? expiresAt;
  final String? createdAt;

  const Invite({
    this.id,
    this.createdBy,
    this.email,
    required this.token,
    this.used = false,
    this.expiresAt,
    this.createdAt,
  });

  bool get isExpired {
    if (expiresAt == null) return false;
    return DateTime.now().isAfter(DateTime.parse(expiresAt!));
  }

  bool get isActive => !used && !isExpired;

  factory Invite.fromJson(Map<String, dynamic> json) {
    return Invite(
      id: json['id'] as String?,
      createdBy: json['created_by'] as String?,
      email: json['email'] as String?,
      token: json['token'] as String,
      used: json['used'] as bool? ?? false,
      expiresAt: json['expires_at'] as String?,
      createdAt: json['created_at'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'created_by': createdBy,
      'email': email,
      'token': token,
      'used': used,
      'expires_at': expiresAt,
      'created_at': createdAt,
    };
  }
}
