#!/usr/bin/env bash
#
# Generate CHANGELOG.md from the git commit history.
#
# The Flutter app ships CHANGELOG.md as an asset and renders it in the
# "What's New" screen (lib/screens/changelog_screen.dart). Re-run this script
# after making commits — see the "Changelog / What's New" section in AGENTS.md.
#
# The Dockerfile also runs this during the image build (best effort) so the
# hosted instance always reflects the history it was built from.
#
# Usage:
#   tool/generate_changelog.sh [max_commits]
#
# Defaults to the 300 most recent non-merge commits, newest first.
set -euo pipefail

cd "$(dirname "$0")/.."

MAX_COMMITS="${1:-300}"
OUT="CHANGELOG.md"

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "error: not inside a git work tree" >&2
  exit 1
fi

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# Changelog"
  echo
  echo "<!-- Generated by tool/generate_changelog.sh from the git history."
  echo "     Do not edit by hand — update the script or its output instead. -->"
  echo

  current_date=""
  # Newest first, grouped by commit date. Fields: date <TAB> subject <TAB> hash.
  git log \
    --no-merges \
    --date=short \
    --pretty=format:'%ad%x09%s%x09%h' \
    -n "$MAX_COMMITS" |
    while IFS=$'\t' read -r date subject hash; do
      [ -z "$date" ] && continue
      if [ "$date" != "$current_date" ]; then
        [ -n "$current_date" ] && echo
        echo "## $date"
        echo
        current_date="$date"
      fi
      echo "- $subject (\`$hash\`)"
    done
} >"$TMP"

mv "$TMP" "$OUT"
trap - EXIT

# mktemp creates 0600 files; make the asset world-readable so the nginx
# worker can serve it (and so it behaves like a normal checked-in file).
chmod 644 "$OUT"

echo "Wrote $OUT from $(git rev-list --count HEAD) commits."
